version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.3.0
    - 5.4.0
    - 5.6.0
    - 5.7.0
    - 5.7.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby-remark-images
    versions:
    - 4.0.0
    - 4.1.0
    - 4.1.1
    - 4.2.0
    - 5.0.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
